# Generated by Django 6.0.2 on 2026-02-15 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('rolename', models.CharField(choices=[('jobseeker', 'Jobseeker'), ('employer', 'Employer')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobseeker_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField()),
                ('experience_years', models.IntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('Image', models.FileField(blank=True, null=True, upload_to='Profile_Image/')),
                ('Id_proof', models.FileField(blank=True, null=True, upload_to='Idproofs/')),
                ('preffered_location', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.register_master')),
            ],
        ),
    ]
