# Generated by Django 6.0.2 on 2026-02-15 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_profile_update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=100, unique=True)),
                ('Designation', models.CharField(max_length=30)),
                ('job_profile', models.CharField(max_length=100)),
                ('company_Name', models.CharField(max_length=40)),
                ('company_details', models.TextField()),
                ('company_address', models.TextField()),
                ('company_website', models.URLField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.register_master')),
            ],
        ),
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_name', models.CharField(max_length=30)),
                ('Job_Type', models.CharField(choices=[('FullTime', 'Fultime'), ('PartTime', 'Part-tiem'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=30)),
                ('Job_Skill', models.CharField(max_length=30)),
                ('Experience', models.IntegerField()),
                ('Qualification', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=30)),
                ('vacancies', models.CharField(max_length=30)),
                ('opening_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.emp_profile_update')),
            ],
        ),
    ]
