# Generated by Django 6.0.2 on 2026-03-03 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Employer', '0001_initial'),
        ('Job', '0003_alter_jobapplication_status_savedjob'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('user', 'job')},
        ),
    ]
